### ISSUE TITLE
'TemporalMemory' object has no attribute 'predictiveCells'

### ISSUE THREAD

**Issue by fursty** [htm-community/nupic.studio#38]
**Pulling up any of the demo files it comes back with this error** 
fursty@fursty-virtual-machine:~$ nupic_studio
Traceback (most recent call last):
  File "/home/fursty/.local/lib/python2.7/site-packages/nupic_studio/ui/main_form.py", line 480, in __buttonInitHTM_Click
    Global.project.network.nextStep()
  File "/home/fursty/.local/lib/python2.7/site-packages/nupic_studio/htm/network.py", line 68, in nextStep
    node.nextStep()
  File "/home/fursty/.local/lib/python2.7/site-packages/nupic_studio/htm/node_region.py", line 274, in nextStep
    self.updateSpatialElements(activeColumns)
  File "/home/fursty/.local/lib/python2.7/site-packages/nupic_studio/htm/node_region.py", line 342, in updateSpatialElements
    if cell.index in self.temporalPooler.predictiveCells:
AttributeError: 'TemporalMemory' object has no attribute 'predictiveCells'

**Comment by rhyolight** [comment]
You probably need to install an older version of NuPIC because NuPIC-Studio has not been maintained for awhile.

**Comment by Oblynx** [comment]
@fursty Did you succeed? Which nupic version did you install?
