### ISSUE TITLE
Errors on initializing  

### ISSUE THREAD

**Issue by gihanmendis** [htm-community/nupic.studio#39]
Hi, I am new to NuPIC. I feel nupic_studio is a faster way to use and understand the concepts. I install nupic_studio following the instructions in the wiki and was following the simulation section in wiki, wanted to try and example project but when clicking on the Initialize button after opening a project I get following errors: 
Traceback (most recent call last):
  File "/home/gihan/nupic.studio-master/nupic_studio/ui/main_form.py", line 465, in __buttonInitHTM_Click
    initialized = Global.project.network.initialize()
  File "/home/gihan/nupic.studio-master/nupic_studio/htm/network.py", line 54, in initialize
    initialized = node.initialize()
  File "/home/gihan/nupic.studio-master/nupic_studio/htm/node_region.py", line 229, in initialize
    spVerbosity = False)
TypeError: __init__() got an unexpected keyword argument 'maxBoost'

I used virtualenv with python2.7 
I install nupic using the command  pip install nupic 
and PyQt4 by using apt-get install python-qt4 python-qt4-gl

I really appreciate if someone can provide me with a solution, thank you verymuch

**Comment by david-ragazzi** [comment]
Please look this:

https://github.com/htm-community/nupic.studio/issues/41
